# Generated by Django 4.0.3 on 2023-07-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OEEData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('availability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quality', models.DecimalField(decimal_places=2, max_digits=5)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oee_dashboard_app.equipment')),
            ],
        ),
    ]
