# Generated by Django 5.1.2 on 2025-05-08 06:49

import oee_dashboard_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ErrorDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "NameOfAlarm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Alarm_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Timing",
                    models.DateTimeField(
                        blank=True,
                        default=oee_dashboard_app.models.current_datetime,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Errorlabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ErrorName", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ErrorBit",
                    models.IntegerField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalOeeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "production",
                    models.IntegerField(blank=True, max_length=50, null=True),
                ),
                (
                    "performance",
                    models.IntegerField(blank=True, max_length=50, null=True),
                ),
                (
                    "availability",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("quality", models.CharField(blank=True, max_length=50, null=True)),
                ("oee", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "logged_on",
                    models.DateTimeField(
                        blank=True,
                        default=oee_dashboard_app.models.current_datetime1,
                        null=True,
                    ),
                ),
                ("defec", models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OEEData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DateTime",
                    models.DateTimeField(
                        blank=True,
                        default=oee_dashboard_app.models.current_datetime,
                        null=True,
                    ),
                ),
                (
                    "Production",
                    models.IntegerField(blank=True, max_length=50, null=True),
                ),
                (
                    "Defective",
                    models.IntegerField(blank=True, max_length=50, null=True),
                ),
                ("Runtime_is", models.CharField(blank=True, max_length=50, null=True)),
                ("Planed_time", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="parameterlabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "runnig_bit",
                    models.IntegerField(blank=True, max_length=100, null=True),
                ),
                (
                    "production_bit",
                    models.IntegerField(blank=True, max_length=100, null=True),
                ),
                (
                    "scrap_bit",
                    models.IntegerField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PopupDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Descriptionis", models.CharField(max_length=50)),
                ("BreakStartTime", models.CharField(max_length=50)),
                ("BreakStopTime", models.CharField(max_length=50)),
                ("EmailRequested", models.EmailField(max_length=50)),
                ("Emailaproved", models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ShiftData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Shift_Start", models.CharField(max_length=50)),
                ("Shift_End", models.CharField(max_length=50)),
                ("Tea_break_1_Start", models.CharField(max_length=50)),
                ("Tea_break_1_Stop", models.CharField(max_length=50)),
                ("lunch_break_start", models.CharField(max_length=50)),
                ("lunch_break_stop", models.CharField(max_length=50)),
                ("Tea_break_2_Start", models.CharField(max_length=50)),
                ("Tea_break_2_Stop", models.CharField(max_length=50)),
            ],
        ),
    ]
