# Generated by Django 4.1.7 on 2023-07-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shift_Start', models.CharField(max_length=50)),
                ('Shift_End', models.CharField(max_length=50)),
                ('Tea_break_1_Start', models.CharField(max_length=50)),
                ('Tea_break_1_Stop', models.CharField(max_length=50)),
                ('lunch_break_start', models.CharField(max_length=50)),
                ('lunch_break_stop', models.CharField(max_length=50)),
                ('Tea_break_2_Start', models.CharField(max_length=50)),
                ('Tea_break_2_Stop', models.CharField(max_length=50)),
            ],
        ),
    ]
