# Generated by Django 4.1.7 on 2023-07-27 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0002_shiftdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeedata',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='oeedata',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='oeedata',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='oeedata',
            name='quality',
        ),
        migrations.AddField(
            model_name='oeedata',
            name='Defective',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oeedata',
            name='Production',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oeedata',
            name='Runtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 27, 15, 58, 30, 380787), null=True),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
