# Generated by Django 4.1.7 on 2023-07-27 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0003_remove_oeedata_availability_remove_oeedata_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeedata',
            name='avalabilty',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 7, 27, 17, 38, 32, 744067), null=True),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 27, 17, 38, 32, 744067), null=True),
        ),
    ]
