# Generated by Django 4.1.7 on 2023-07-27 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0004_oeedata_avalabilty_alter_oeedata_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeedata',
            name='avalabilty',
        ),
        migrations.AddField(
            model_name='oeedata',
            name='availabilty',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 7, 27, 17, 50, 40, 445695), null=True),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 27, 17, 50, 40, 445695), null=True),
        ),
    ]
