# Generated by Django 4.1.7 on 2023-07-28 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0005_remove_oeedata_avalabilty_oeedata_availabilty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descriptionis', models.CharField(max_length=50)),
                ('BreakStartTime', models.CharField(max_length=50)),
                ('BreakStopTime', models.CharField(max_length=50)),
                ('EmailRequested', models.EmailField(max_length=50)),
                ('Emailaproved', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 28, 12, 32, 1, 316510), null=True),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='availabilty',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 7, 28, 12, 32, 1, 316510), null=True),
        ),
    ]
