# Generated by Django 4.1.7 on 2023-08-01 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0006_popupdatamodel_alter_oeedata_runtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeedata',
            name='date',
        ),
        migrations.AddField(
            model_name='oeedata',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 1, 12, 16, 36, 933046)),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 1, 12, 16, 36, 933046), null=True),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='availabilty',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 8, 1, 12, 16, 36, 933046), null=True),
        ),
    ]
