# Generated by Django 4.1.7 on 2023-08-01 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0007_remove_oeedata_date_oeedata_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='availabilty',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
