# Generated by Django 4.1.7 on 2023-08-01 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0008_alter_oeedata_datetime_alter_oeedata_runtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.TimeField(blank=True, default=datetime.time(8, 25, 22, 685708)),
        ),
    ]
