# Generated by Django 4.1.7 on 2023-08-01 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0009_alter_oeedata_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 8, 1, 15, 20, 39, 516610)),
        ),
    ]
