# Generated by Django 4.1.7 on 2023-08-01 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0010_alter_oeedata_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
