# Generated by Django 4.1.7 on 2023-08-01 10:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0011_alter_oeedata_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.DateTimeField(blank=True, default=datetime.time(10, 11, 23, 905680)),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='availabilty',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
