# Generated by Django 4.1.7 on 2023-08-01 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0013_alter_oeedata_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
