# Generated by Django 4.1.7 on 2023-08-01 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0014_alter_oeedata_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='oeedata',
            name='availabilty',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
