# Generated by Django 4.1.7 on 2023-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0015_alter_oeedata_datetime_alter_oeedata_availabilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeedata',
            name='Planed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
