# Generated by Django 4.1.7 on 2023-08-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0016_oeedata_planed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='Planed_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
