# Generated by Django 4.1.7 on 2023-08-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0017_alter_oeedata_planed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeedata',
            name='Runtime',
        ),
        migrations.RemoveField(
            model_name='oeedata',
            name='availabilty',
        ),
        migrations.AddField(
            model_name='oeedata',
            name='Runtime_is',
            field=models.CharField(blank=True, default=300, max_length=50),
        ),
    ]
