# Generated by Django 4.1.7 on 2023-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0018_remove_oeedata_runtime_remove_oeedata_availabilty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime_is',
            field=models.CharField(blank=True, default=70, max_length=50),
        ),
    ]
