# Generated by Django 4.1.7 on 2023-08-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0019_alter_oeedata_runtime_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='Runtime_is',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
