# Generated by Django 4.1.7 on 2023-08-07 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0020_alter_oeedata_runtime_is'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalOeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.IntegerField(blank=True, max_length=50, null=True)),
                ('performance', models.IntegerField(blank=True, max_length=50, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('oee', models.CharField(blank=True, max_length=50, null=True)),
                ('logged_on', models.DateField(default=datetime.date(2023, 8, 7))),
            ],
        ),
    ]
