# Generated by Django 4.1.7 on 2023-08-07 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0021_finaloeedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaloeedata',
            name='logged_on',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 7, 12, 25, 28, 352590)),
        ),
    ]
