# Generated by Django 4.1.7 on 2023-08-07 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0022_alter_finaloeedata_logged_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaloeedata',
            name='logged_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 7, 12, 26, 45, 131879)),
        ),
    ]
