# Generated by Django 4.1.7 on 2023-08-07 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0023_alter_finaloeedata_logged_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaloeedata',
            name='logged_on',
            field=models.DateTimeField(default=datetime.date(2023, 8, 7)),
        ),
    ]
