# Generated by Django 4.1.7 on 2023-09-14 06:14

from django.db import migrations, models
import oee_dashboard_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0025_alter_finaloeedata_logged_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeedata',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=oee_dashboard_app.models.current_datetime, null=True),
        ),
    ]
