# Generated by Django 4.1.7 on 2023-09-29 13:40

import datetime
from django.db import migrations, models
import oee_dashboard_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0026_alter_oeedata_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfAlarm', models.CharField(blank=True, max_length=100, null=True)),
                ('Alarm_value', models.CharField(blank=True, max_length=100, null=True)),
                ('Timing', models.DateTimeField(blank=True, default=oee_dashboard_app.models.current_datetime, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='finaloeedata',
            name='logged_on',
            field=models.DateTimeField(default=datetime.date(2023, 9, 29)),
        ),
    ]
