# Generated by Django 4.0.3 on 2024-02-28 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0027_errordb_alter_finaloeedata_logged_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaloeedata',
            name='logged_on',
            field=models.DateTimeField(default=datetime.date(2024, 2, 28)),
        ),
    ]
