# Generated by Django 5.0.2 on 2024-03-08 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0028_alter_finaloeedata_logged_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaloeedata',
            name='defec',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finaloeedata',
            name='logged_on',
            field=models.DateTimeField(default=datetime.date(2024, 3, 8)),
        ),
    ]
