# Generated by Django 5.0.2 on 2024-03-08 07:05

import oee_dashboard_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0029_finaloeedata_defec_alter_finaloeedata_logged_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaloeedata',
            name='logged_on',
            field=models.DateTimeField(blank=True, default=oee_dashboard_app.models.current_datetime, null=True),
        ),
    ]
