# Generated by Django 5.1.2 on 2024-12-03 07:32

import oee_dashboard_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0030_alter_finaloeedata_logged_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errorlabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErrorName', models.CharField(blank=True, max_length=100, null=True)),
                ('ErrorBit', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='finaloeedata',
            name='logged_on',
            field=models.DateTimeField(blank=True, default=oee_dashboard_app.models.current_datetime1, null=True),
        ),
    ]
