# Generated by Django 5.1.2 on 2024-12-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_dashboard_app', '0031_errorlabels_alter_finaloeedata_logged_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='parameterlabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runnig_bit', models.IntegerField(blank=True, max_length=100, null=True)),
                ('production_bit', models.IntegerField(blank=True, max_length=100, null=True)),
                ('scrap_bit', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
